
services:

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  eureka-server:
    image: eureka-server
    build:
      context: ./Service-registry
    container_name: eureka-server
    ports:
      - "8181:8181"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - backend

  student-service:
    image: student-service
    build:
      context: ./student-service
    container_name: student-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
    networks:
      - backend

  course-service:
    image: course-service
    build:
      context: ./course-service
    container_name: course-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
      - student-service
    networks:
      - backend

  enrollment-service:
    image: enrollment-service
    build:
      context: ./Enrollment-Service
    container_name: enrollment-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
      - course-service
      - student-service
    networks:
      - backend

  feedback-service:
    image: feedback-service
    build:
      context: ./Feedback-Service
    container_name: feedback-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - eureka-server
      - enrollment-service
    networks:
      - backend

  notification-service:
    image: notification-service
    build:
      context: ./Notification-Service
    container_name: notification-service
    environment:
       SPRING_PROFILES_ACTIVE: docker
       MAIL_HOST: smtp.gmail.com
       MAIL_PORT: 587
       MAIL_USERNAME: sarbudeen8124@gmail.com
       MAIL_PASSWORD: ppcyslzsajizeyms
       MAIL_PROTOCOL: smtp
      
    depends_on:
      - rabbitmq
      - eureka-server
    networks:
      - backend

  api-gateway:
    image: api-gateway
    build:
      context: ./Api-gateway-service
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
    networks:
      - backend

networks:
  backend:
    driver: bridge
