services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports: ['5432:5432']

  rabbitmq:
    image: rabbitmq:3-management
    ports: ['5672:5672','15672:15672']

  eureka-server:
    build: ./Service-registry
    ports: ['8181:8181']
    depends_on: [postgres]

  student-service:
    build: ./student-service
    ports: ['8081:8081']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [eureka-server,postgres,rabbitmq]

  course-service:
    build: ./course-service
    ports: ['8082:8082']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [eureka-server,postgres,student-service]

  enrollment-service:
    build: ./enrollment-service
    ports: ['8083:8083']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [eureka-server,postgres,course-service,student-service]

  feedback-service:
    build: ./feedback-service
    ports: ['8084:8084']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [eureka-server,postgres,enrollment-service]

  notification-service:
    build: ./notification-service
    ports: ['8085:8085']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_app_pass
    depends_on: [rabbitmq,eureka-server]

  api-gateway:
    build: ./Api-gateway-service
    ports: ['8080:8080']
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on: [eureka-server]

volumes:
  db-data: