spring.application.name=api-gateway
server.port=8081

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.preferIpAddress=true

spring.cloud.gateway.routes[0].id=student-service
spring.cloud.gateway.routes[0].uri=lb://student-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/students/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/students(?<segment>/?.*), /api/students$\{segment}

spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=lb://course-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/courses/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/courses(?<segment>/?.*), /api/courses$\{segment}

spring.cloud.gateway.routes[2].id=enrollment-service
spring.cloud.gateway.routes[2].uri=lb://enrollment-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/enrollments/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/enrollments(?<segment>/?.*), /api/enrollments$\{segment}
